### ISSUE TITLE
Bug with ban people

### ISSUE THREAD

**Issue by slaVACo** [Maks-s/ghostban#1]
Suppose to ban the person for 1 minute, he Perezhogin and vole he permaban why

**Comment by slaVACo** [comment]
and to be precise, to ban yourself for 1 minute after standing on the server waiting for, then how come 1 minute peresechenii and vole you got Perma ban

**Comment by Maks-s** [comment]
Thanks for reporting the issue, fixed in commit 78b10900a6028aeda7ae470552ffe7a15c675881
